// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6BmDY9-XAfR3akhKKP1ggJ7DEa4zYIR8',
    appId: '1:24219077731:web:6917f9153a04e8b46c7c56',
    messagingSenderId: '24219077731',
    projectId: 'mini-chat-app-bd3a5',
    authDomain: 'mini-chat-app-bd3a5.firebaseapp.com',
    storageBucket: 'mini-chat-app-bd3a5.firebasestorage.app',
    measurementId: 'G-6C318LY3B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxyK5yFDB4-HfaTb_IOZXrnRNz5X3wLXw',
    appId: '1:24219077731:android:3f24b74835a5b4c76c7c56',
    messagingSenderId: '24219077731',
    projectId: 'mini-chat-app-bd3a5',
    storageBucket: 'mini-chat-app-bd3a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYGC06bz0yDvYgXwWaZ6RhbY0ShQnHTs',
    appId: '1:24219077731:ios:98406c62c710161e6c7c56',
    messagingSenderId: '24219077731',
    projectId: 'mini-chat-app-bd3a5',
    storageBucket: 'mini-chat-app-bd3a5.firebasestorage.app',
    iosBundleId: 'com.example.miniChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYGC06bz0yDvYgXwWaZ6RhbY0ShQnHTs',
    appId: '1:24219077731:ios:98406c62c710161e6c7c56',
    messagingSenderId: '24219077731',
    projectId: 'mini-chat-app-bd3a5',
    storageBucket: 'mini-chat-app-bd3a5.firebasestorage.app',
    iosBundleId: 'com.example.miniChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6BmDY9-XAfR3akhKKP1ggJ7DEa4zYIR8',
    appId: '1:24219077731:web:ba9a819baf24554f6c7c56',
    messagingSenderId: '24219077731',
    projectId: 'mini-chat-app-bd3a5',
    authDomain: 'mini-chat-app-bd3a5.firebaseapp.com',
    storageBucket: 'mini-chat-app-bd3a5.firebasestorage.app',
    measurementId: 'G-XEVEX04M2B',
  );
}
